apiVersion: v1
kind: Secret
metadata:
  name: github
type: Opaque
data:
  oauth-token: {{ .Values.github.oAuthToken | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab
type: Opaque
data:
  oauth-token: {{ .Values.gitlab.oAuthToken | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghdocker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}